using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Threading.Channels;
using Nexum.Abstractions;
using Nexum.Internal;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;

namespace Nexum.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for registering Nexum CQRS services with <see cref="IServiceCollection"/>.
/// </summary>
public static class NexumServiceCollectionExtensions
{
    private static readonly Type[] s_behaviorOpenGenericTypes =
    [
        typeof(ICommandBehavior<,>),
        typeof(IQueryBehavior<,>),
        typeof(IStreamQueryBehavior<,>)
    ];

    private static readonly Type[] s_exceptionHandlerOpenGenericTypes =
    [
        typeof(ICommandExceptionHandler<,>),
        typeof(IQueryExceptionHandler<,>),
        typeof(INotificationExceptionHandler<,>)
    ];

    private static readonly Type[] s_handlerOpenGenericTypes =
    [
        typeof(ICommandHandler<,>),
        typeof(IQueryHandler<,>),
        typeof(IStreamQueryHandler<,>),
        typeof(INotificationHandler<>)
    ];

    /// <summary>
    /// Registers all Nexum CQRS infrastructure services including dispatchers, pipeline components,
    /// and optionally discovers handlers from the provided assemblies.
    /// </summary>
    /// <remarks>
    /// <para>Handler discovery modes:</para>
    /// <list type="number">
    /// <item>If a <c>NexumHandlerRegistry</c> type is found in <paramref name="assemblies"/> (generated by Nexum.SourceGenerators),
    /// its explicit registrations are used (AOT-safe).</item>
    /// <item>If no registry is found and <paramref name="assemblies"/> are provided, assembly scanning discovers handlers via reflection.</item>
    /// <item>If no registry is found and no assemblies are provided, an <see cref="InvalidOperationException"/> is thrown.</item>
    /// </list>
    /// </remarks>
    /// <param name="services">The service collection to add Nexum services to.</param>
    /// <param name="configure">Optional configuration action for <see cref="NexumOptions"/>.</param>
    /// <param name="assemblies">Assemblies to scan for handlers. Required when not using Nexum.SourceGenerators.</param>
    /// <returns>The service collection for chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when no handler registry is found and no assemblies are provided.</exception>
    [RequiresUnreferencedCode("Assembly scanning uses reflection to discover handler types. Use Nexum.SourceGenerators for AOT-safe registration.")]
    [RequiresDynamicCode("Assembly scanning uses MakeGenericType for handler interface matching. Use Nexum.SourceGenerators for AOT-safe registration.")]
    public static IServiceCollection AddNexum(
        this IServiceCollection services,
        Action<NexumOptions>? configure = null,
        params Assembly[] assemblies)
    {
        ArgumentNullException.ThrowIfNull(services);

        // Configure options — fail-fast (property setters throw ArgumentOutOfRangeException)
        var options = new NexumOptions();
        configure?.Invoke(options);

        // Apply behavior order overrides registered via AddNexumBehavior(order:)
        foreach (ServiceDescriptor descriptor in services)
        {
            if (descriptor.ServiceType == typeof(BehaviorOrderRegistration)
                && descriptor.ImplementationInstance is BehaviorOrderRegistration registration)
            {
                options.BehaviorOrderOverrides[registration.BehaviorType] = registration.Order;
            }
        }

        services.AddSingleton(options);

        // Register core infrastructure
        services.TryAddSingleton<ExceptionHandlerResolver>();
        services.TryAddSingleton<ICommandDispatcher, CommandDispatcher>();
        services.TryAddSingleton<IQueryDispatcher, QueryDispatcher>();

        // Register bounded channel for FireAndForget notifications
        var channel = Channel.CreateBounded<NotificationEnvelope>(
            new BoundedChannelOptions(options.FireAndForgetChannelCapacity)
            {
                FullMode = BoundedChannelFullMode.Wait,
                SingleReader = true,
                SingleWriter = false
            });
        services.AddSingleton(channel.Reader);
        services.AddSingleton(channel.Writer);

        services.TryAddSingleton<INotificationPublisher>(sp =>
            new NotificationPublisher(
                sp,
                sp.GetRequiredService<NexumOptions>(),
                sp.GetRequiredService<ChannelWriter<NotificationEnvelope>>()));

        // Register background service for FireAndForget notifications
        services.AddSingleton<IHostedService, NotificationBackgroundService>();

        // Handler discovery
        Type? registryType = FindHandlerRegistry(assemblies);
        if (registryType is not null)
        {
            MethodInfo addMethod = registryType.GetMethod("AddNexumHandlers", BindingFlags.Public | BindingFlags.Static) ?? throw new InvalidOperationException(
                    $"NexumHandlerRegistry type '{registryType.FullName}' does not have a public static AddNexumHandlers method.");
            addMethod.Invoke(null, [services]);
        }
        else if (assemblies.Length > 0)
        {
            ScanAndRegisterHandlers(services, assemblies);
        }
        else
        {
            throw new InvalidOperationException(
                "No NexumHandlerRegistry found and no assemblies provided. " +
                "Either add the Nexum.SourceGenerators package or provide assemblies via the 'assemblies' parameter: " +
                "services.AddNexum(assemblies: typeof(MyHandler).Assembly)");
        }

        // Tier 2: Detect NexumPipelineRegistry (generated by Nexum.SourceGenerators)
        Type? pipelineRegistryType = FindPipelineRegistry(assemblies);
        if (pipelineRegistryType is not null)
        {
            options.PipelineRegistryType = pipelineRegistryType;
        }

        return services;
    }

    /// <summary>
    /// Registers a handler with the specified service and implementation types.
    /// </summary>
    /// <typeparam name="TService">The handler interface type.</typeparam>
    /// <typeparam name="TImplementation">The handler implementation type.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <param name="lifetime">The handler lifetime. Defaults to <see cref="NexumLifetime.Scoped"/>.</param>
    /// <returns>The service collection for chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is null.</exception>
    public static IServiceCollection AddNexumHandler<TService, TImplementation>(
        this IServiceCollection services,
        NexumLifetime lifetime = NexumLifetime.Scoped)
        where TService : class
        where TImplementation : class, TService
    {
        ArgumentNullException.ThrowIfNull(services);

        services.Add(new ServiceDescriptor(
            typeof(TService),
            typeof(TImplementation),
            NexumLifetimeMapper.ToServiceLifetime(lifetime)));

        return services;
    }

    /// <summary>
    /// Registers an open-generic behavior type for the Nexum pipeline.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The behavior type is automatically registered for each behavior interface it implements
    /// (<see cref="ICommandBehavior{TCommand,TResult}"/>, <see cref="IQueryBehavior{TQuery,TResult}"/>,
    /// <see cref="IStreamQueryBehavior{TQuery,TResult}"/>).
    /// </para>
    /// <para>
    /// When <paramref name="order"/> is specified, it overrides any <c>[BehaviorOrder]</c> attribute
    /// on the behavior type. Lower values execute first (outermost in the Russian doll pipeline).
    /// </para>
    /// </remarks>
    /// <param name="services">The service collection.</param>
    /// <param name="behaviorType">The open-generic behavior type to register.</param>
    /// <param name="order">Optional explicit ordering that overrides <c>[BehaviorOrder]</c> attribute.</param>
    /// <param name="lifetime">The behavior lifetime. Defaults to <see cref="NexumLifetime.Transient"/>.</param>
    /// <returns>The service collection for chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> or <paramref name="behaviorType"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown when <paramref name="behaviorType"/> does not implement any behavior interface.</exception>
    public static IServiceCollection AddNexumBehavior(
        this IServiceCollection services,
        Type behaviorType,
        int? order = null,
        NexumLifetime lifetime = NexumLifetime.Transient)
    {
        ArgumentNullException.ThrowIfNull(services);
        ArgumentNullException.ThrowIfNull(behaviorType);

        var serviceLifetime = NexumLifetimeMapper.ToServiceLifetime(lifetime);
        bool registered = false;

        foreach (Type iface in behaviorType.GetInterfaces())
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            Type genericDef = iface.GetGenericTypeDefinition();
            bool isMatch = false;

            foreach (Type openType in s_behaviorOpenGenericTypes)
            {
                if (genericDef == openType)
                {
                    isMatch = true;
                    if (behaviorType.IsGenericTypeDefinition)
                    {
                        services.Add(new ServiceDescriptor(openType, behaviorType, serviceLifetime));
                    }
                    else
                    {
                        services.Add(new ServiceDescriptor(iface, behaviorType, serviceLifetime));
                    }
                    break;
                }
            }

            if (isMatch)
            {
                registered = true;
            }
        }

        if (!registered)
        {
            throw new ArgumentException(
                $"Type '{behaviorType.FullName}' does not implement any Nexum behavior interface " +
                $"(ICommandBehavior<,>, IQueryBehavior<,>, IStreamQueryBehavior<,>).",
                nameof(behaviorType));
        }

        // Store order override as a marker service, collected by AddNexum()
        if (order.HasValue)
        {
            services.AddSingleton(new BehaviorOrderRegistration(behaviorType, order.Value));
        }

        return services;
    }

    /// <summary>
    /// Registers an exception handler for the Nexum pipeline.
    /// </summary>
    /// <typeparam name="THandler">The exception handler implementation type.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <param name="lifetime">The handler lifetime. Defaults to <see cref="NexumLifetime.Transient"/>.</param>
    /// <returns>The service collection for chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown when <typeparamref name="THandler"/> does not implement any exception handler interface.</exception>
    public static IServiceCollection AddNexumExceptionHandler<THandler>(
        this IServiceCollection services,
        NexumLifetime lifetime = NexumLifetime.Transient)
        where THandler : class
    {
        ArgumentNullException.ThrowIfNull(services);

        Type handlerType = typeof(THandler);
        var serviceLifetime = NexumLifetimeMapper.ToServiceLifetime(lifetime);
        bool registered = false;

        foreach (Type iface in handlerType.GetInterfaces())
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            Type genericDef = iface.GetGenericTypeDefinition();

            foreach (Type openType in s_exceptionHandlerOpenGenericTypes)
            {
                if (genericDef == openType)
                {
                    services.Add(new ServiceDescriptor(iface, handlerType, serviceLifetime));
                    registered = true;
                    break;
                }
            }
        }

        return !registered
            ? throw new ArgumentException(
                $"Type '{handlerType.FullName}' does not implement any Nexum exception handler interface " +
                $"(ICommandExceptionHandler<,>, IQueryExceptionHandler<,>, INotificationExceptionHandler<,>).",
                nameof(THandler))
            : services;
    }

    /// <summary>
    /// Registers a result adapter that enables behaviors to inspect result types.
    /// </summary>
    /// <typeparam name="TAdapter">The result adapter implementation type.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown when <typeparamref name="TAdapter"/> does not implement <c>IResultAdapter&lt;&gt;</c>.</exception>
    public static IServiceCollection AddNexumResultAdapter<TAdapter>(
        this IServiceCollection services)
        where TAdapter : class
    {
        ArgumentNullException.ThrowIfNull(services);

        Type adapterType = typeof(TAdapter);
        bool registered = false;

        foreach (Type iface in adapterType.GetInterfaces())
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            if (iface.GetGenericTypeDefinition() == typeof(IResultAdapter<>))
            {
                services.AddSingleton(iface, adapterType);
                registered = true;
            }
        }

        return !registered
            ? throw new ArgumentException(
                $"Type '{adapterType.FullName}' does not implement IResultAdapter<>.",
                nameof(TAdapter))
            : services;
    }

    // ── Private helpers ──

    [RequiresUnreferencedCode("Assembly scanning uses reflection.")]
    [RequiresDynamicCode("Assembly scanning uses MakeGenericType.")]
    private static Type? FindHandlerRegistry(Assembly[] assemblies)
    {
        foreach (Assembly assembly in assemblies)
        {
            foreach (Type type in assembly.GetTypes())
            {
                if (type.Name == "NexumHandlerRegistry" && !type.IsNested)
                {
                    return type;
                }
            }
        }
        return null;
    }

    [RequiresUnreferencedCode("Assembly scanning uses reflection.")]
    [RequiresDynamicCode("Assembly scanning uses MakeGenericType.")]
    private static Type? FindPipelineRegistry(Assembly[] assemblies)
    {
        foreach (Assembly assembly in assemblies)
        {
            foreach (Type type in assembly.GetTypes())
            {
                if (type.Name == "NexumPipelineRegistry" && !type.IsNested)
                {
                    return type;
                }
            }
        }
        return null;
    }

    [RequiresUnreferencedCode("Assembly scanning uses reflection.")]
    [RequiresDynamicCode("Assembly scanning uses MakeGenericType.")]
    private static void ScanAndRegisterHandlers(IServiceCollection services, Assembly[] assemblies)
    {
        foreach (Assembly assembly in assemblies)
        {
            foreach (Type type in assembly.GetExportedTypes())
            {
                if (type.IsAbstract || type.IsInterface || type.IsGenericTypeDefinition)
                {
                    continue;
                }

                RegisterHandlerInterfaces(services, type);
            }
        }
    }

    private static void RegisterHandlerInterfaces(IServiceCollection services, Type implementationType)
    {
        HandlerLifetimeAttribute? lifetimeAttr = implementationType.GetCustomAttribute<HandlerLifetimeAttribute>();
        ServiceLifetime serviceLifetime = lifetimeAttr is not null
            ? NexumLifetimeMapper.ToServiceLifetime(lifetimeAttr.Lifetime)
            : ServiceLifetime.Scoped;

        foreach (Type iface in implementationType.GetInterfaces())
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            Type genericDef = iface.GetGenericTypeDefinition();

            foreach (Type handlerType in s_handlerOpenGenericTypes)
            {
                if (genericDef == handlerType)
                {
                    services.Add(new ServiceDescriptor(iface, implementationType, serviceLifetime));
                }
            }
        }
    }
}

/// <summary>
/// Internal marker for behavior order overrides registered via <see cref="NexumServiceCollectionExtensions.AddNexumBehavior"/>.
/// Collected by <see cref="NexumServiceCollectionExtensions.AddNexum"/> during initialization.
/// </summary>
internal sealed record BehaviorOrderRegistration(Type BehaviorType, int Order);
