//HintName: NexumInterceptors.g.cs
// <auto-generated/>
#nullable enable

#pragma warning disable CS9113 // Parameter is unread
namespace System.Runtime.CompilerServices
{
    using System;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
}
#pragma warning restore CS9113

namespace TestApp.Generated
{
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Auto-generated interceptor methods for Nexum dispatcher calls.
    /// Generated by Nexum.SourceGenerators (Tier 3).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    file static class NexumInterceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "VElvTuNititudRuF68rZ7SIEAAA=")]
        internal static global::System.Threading.Tasks.ValueTask<TResult>
            Intercept_DispatchAsync_0001<TResult>(
                this global::Nexum.Abstractions.ICommandDispatcher @this,
                global::Nexum.Abstractions.ICommand<TResult> command,
                global::System.Threading.CancellationToken ct = default)
        {
            var __result = ((global::Nexum.IInterceptableDispatcher)@this)
                .DispatchInterceptedCommandAsync<global::TestApp.CreateOrderCommand, global::System.Guid>(
                    (global::TestApp.CreateOrderCommand)(object)command,
                    static (cmd, sp, ct) =>
                    {
                        return global::TestApp.NexumPipelineRegistry.Dispatch_TestApp_CreateOrderCommand(cmd, sp, ct);
                    },
                    ct);
            return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<global::System.Guid>, global::System.Threading.Tasks.ValueTask<TResult>>(ref __result);
        }

    }
}
