//HintName: NexumInterceptors.g.cs
// <auto-generated/>
#nullable enable

#pragma warning disable CS9113 // Parameter is unread
namespace System.Runtime.CompilerServices
{
    using System;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
}
#pragma warning restore CS9113

namespace TestApp.Generated
{
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Auto-generated interceptor methods for Nexum dispatcher calls.
    /// Generated by Nexum.SourceGenerators (Tier 3).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    file static class NexumInterceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xn1A0WPGNH9hxK8kfR7wD88CAAA=")]
        internal static global::System.Threading.Tasks.ValueTask<TResult>
            Intercept_DispatchAsync_0001<TResult>(
                this global::Nexum.Abstractions.IQueryDispatcher @this,
                global::Nexum.Abstractions.IQuery<TResult> query,
                global::System.Threading.CancellationToken ct = default)
        {
            var __result = ((global::Nexum.IInterceptableDispatcher)@this)
                .DispatchInterceptedQueryAsync<global::TestApp.GetOrderQuery, global::System.String>(
                    (global::TestApp.GetOrderQuery)(object)query,
                    static (qry, sp, ct) =>
                    {
                        var handler = global::Microsoft.Extensions.DependencyInjection
                            .ServiceProviderServiceExtensions
                            .GetRequiredService<global::Nexum.Abstractions.IQueryHandler<TestApp.GetOrderQuery, System.String>>(sp);
                        return handler.HandleAsync(qry, ct);
                    },
                    ct);
            return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<global::System.String>, global::System.Threading.Tasks.ValueTask<TResult>>(ref __result);
        }

    }
}
