//HintName: NexumInterceptors.g.cs
// <auto-generated/>
#nullable enable

#pragma warning disable CS9113 // Parameter is unread
namespace System.Runtime.CompilerServices
{
    using System;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
}
#pragma warning restore CS9113

namespace TestApp.Generated
{
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Auto-generated interceptor methods for Nexum dispatcher calls.
    /// Generated by Nexum.SourceGenerators (Tier 3).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    file static class NexumInterceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "cF61tbyz5Tbol/M+G0qawTMDAAA=")]
        internal static global::System.Collections.Generic.IAsyncEnumerable<TResult>
            Intercept_DispatchAsync_0001<TResult>(
                this global::Nexum.Abstractions.IQueryDispatcher @this,
                global::Nexum.Abstractions.IStreamQuery<TResult> query,
                global::System.Threading.CancellationToken ct = default)
        {
            var __result = ((global::Nexum.IInterceptableDispatcher)@this)
                .StreamInterceptedAsync<global::TestApp.StreamOrdersQuery, global::System.String>(
                    (global::TestApp.StreamOrdersQuery)(object)query,
                    static (qry, sp, ct) =>
                    {
                        var handler = global::Microsoft.Extensions.DependencyInjection
                            .ServiceProviderServiceExtensions
                            .GetRequiredService<global::TestApp.StreamOrdersQueryHandler>(sp);
                        return handler.HandleAsync(qry, ct);
                    },
                    ct);
            return global::System.Runtime.CompilerServices.Unsafe
                .As<global::System.Collections.Generic.IAsyncEnumerable<global::System.String>,
                    global::System.Collections.Generic.IAsyncEnumerable<TResult>>(ref __result);
        }

    }
}
