//HintName: NexumEndpointRegistration.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    /// <summary>
    /// Auto-generated endpoint registration for Nexum Minimal API endpoints.
    /// Generated by Nexum.SourceGenerators.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    public static class NexumEndpointRegistration
    {
        /// <summary>
        /// Maps all Nexum endpoints decorated with [NexumEndpoint] attribute.
        /// </summary>
        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapNexumEndpoints(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
        {

            endpoints.MapGet("/api/orders/{id}", async (
                [global::Microsoft.AspNetCore.Http.AsParameters] global::TestApp.GetOrderQuery query,
                global::Nexum.Abstractions.IQueryDispatcher dispatcher,
                global::System.Threading.CancellationToken ct) =>
            {
                var result = await dispatcher.DispatchAsync(query, ct).ConfigureAwait(false);
                return global::Microsoft.AspNetCore.Http.TypedResults.Ok(result);
            })
            .WithName("GetOrder")
            .Produces<global::System.String>(200)
            .ProducesProblem(400)
            ;
            return endpoints;
        }
    }
}
