//HintName: NexumHandlerRegistry.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    /// <summary>
    /// Auto-generated handler registry for Nexum DI registration.
    /// Generated by Nexum.SourceGenerators (Tier 1).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    internal static class NexumHandlerRegistry
    {
        /// <summary>
        /// Registers all discovered Nexum handlers with the service collection.
        /// </summary>
        public static void AddNexumHandlers(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                typeof(global::Nexum.Abstractions.ICommandHandler<TestApp.CreateOrderCommand, System.Guid>),
                typeof(global::TestApp.CreateOrderCommandHandler),
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                typeof(global::Nexum.Abstractions.IQueryHandler<TestApp.GetOrderQuery, System.String>),
                typeof(global::TestApp.GetOrderQueryHandler),
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                typeof(global::Nexum.Abstractions.IStreamQueryHandler<TestApp.StreamOrdersQuery, System.String>),
                typeof(global::TestApp.StreamOrdersQueryHandler),
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                typeof(global::Nexum.Abstractions.INotificationHandler<TestApp.OrderCreatedNotification>),
                typeof(global::TestApp.OrderCreatedNotificationHandler),
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));
        }

        /// <summary>
        /// Returns all handler registrations for non-MSDI containers.
        /// </summary>
        public static global::System.Collections.Generic.IEnumerable<(global::System.Type ServiceType, global::System.Type ImplementationType, global::Nexum.Abstractions.NexumLifetime Lifetime)> GetAllRegistrations()
        {
            yield return (typeof(global::Nexum.Abstractions.ICommandHandler<TestApp.CreateOrderCommand, System.Guid>), typeof(global::TestApp.CreateOrderCommandHandler), global::Nexum.Abstractions.NexumLifetime.Scoped);
            yield return (typeof(global::Nexum.Abstractions.IQueryHandler<TestApp.GetOrderQuery, System.String>), typeof(global::TestApp.GetOrderQueryHandler), global::Nexum.Abstractions.NexumLifetime.Scoped);
            yield return (typeof(global::Nexum.Abstractions.IStreamQueryHandler<TestApp.StreamOrdersQuery, System.String>), typeof(global::TestApp.StreamOrdersQueryHandler), global::Nexum.Abstractions.NexumLifetime.Scoped);
            yield return (typeof(global::Nexum.Abstractions.INotificationHandler<TestApp.OrderCreatedNotification>), typeof(global::TestApp.OrderCreatedNotificationHandler), global::Nexum.Abstractions.NexumLifetime.Scoped);
        }
    }
}
