//HintName: NexumPipelineRegistry.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    /// <summary>
    /// Auto-generated pipeline registry with monomorphized dispatch methods.
    /// Generated by Nexum.SourceGenerators (Tier 2).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    internal static class NexumPipelineRegistry
    {
        public static global::System.Threading.Tasks.ValueTask<global::System.Guid>
            Dispatch_TestApp_CreateOrderCommand(
                global::TestApp.CreateOrderCommand command,
                global::System.IServiceProvider sp,
                global::System.Threading.CancellationToken ct)
        {
            var handler = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.CreateOrderCommandHandler>(sp);
            var behavior1 = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.LoggingBehavior<global::TestApp.CreateOrderCommand, global::System.Guid>>(sp);
            var behavior2 = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.ValidationBehavior<global::TestApp.CreateOrderCommand, global::System.Guid>>(sp);
            return behavior1.HandleAsync(command,
                ct2 => behavior2.HandleAsync(command,
                ct3 => handler.HandleAsync(command, ct3), ct2)
                , ct);
        }

        public static global::System.Threading.Tasks.ValueTask<global::System.String>
            Dispatch_TestApp_GetOrderQuery(
                global::TestApp.GetOrderQuery query,
                global::System.IServiceProvider sp,
                global::System.Threading.CancellationToken ct)
        {
            var handler = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.GetOrderQueryHandler>(sp);
            var behavior1 = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.QueryLoggingBehavior<global::TestApp.GetOrderQuery, global::System.String>>(sp);
            return behavior1.HandleAsync(query,
                ct2 => handler.HandleAsync(query, ct2), ct);
        }

        public static global::System.Collections.Generic.IAsyncEnumerable<global::System.String>
            Stream_TestApp_StreamOrdersQuery(
                global::TestApp.StreamOrdersQuery query,
                global::System.IServiceProvider sp,
                global::System.Threading.CancellationToken ct)
        {
            var handler = global::Microsoft.Extensions.DependencyInjection
                .ServiceProviderServiceExtensions
                .GetRequiredService<global::TestApp.StreamOrdersQueryHandler>(sp);
            return handler.HandleAsync(query, ct);
        }


        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> s_commandMethods = new global::System.Collections.Generic.Dictionary<global::System.Type, string>
        {
            [typeof(global::TestApp.CreateOrderCommand)] = nameof(Dispatch_TestApp_CreateOrderCommand),
        };
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> s_queryMethods = new global::System.Collections.Generic.Dictionary<global::System.Type, string>
        {
            [typeof(global::TestApp.GetOrderQuery)] = nameof(Dispatch_TestApp_GetOrderQuery),
        };
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> s_streamQueryMethods = new global::System.Collections.Generic.Dictionary<global::System.Type, string>
        {
            [typeof(global::TestApp.StreamOrdersQuery)] = nameof(Stream_TestApp_StreamOrdersQuery),
        };

        public static bool HasCompiledCommandPipeline(global::System.Type commandType)
            => s_commandMethods.ContainsKey(commandType);

        public static bool HasCompiledQueryPipeline(global::System.Type queryType)
            => s_queryMethods.ContainsKey(queryType);

        public static bool HasCompiledStreamQueryPipeline(global::System.Type queryType)
            => s_streamQueryMethods.ContainsKey(queryType);

        public static string? GetCommandMethodName(global::System.Type commandType)
            => s_commandMethods.TryGetValue(commandType, out var name) ? name : null;

        public static string? GetQueryMethodName(global::System.Type queryType)
            => s_queryMethods.TryGetValue(queryType, out var name) ? name : null;

        public static string? GetStreamQueryMethodName(global::System.Type queryType)
            => s_streamQueryMethods.TryGetValue(queryType, out var name) ? name : null;

        private static readonly global::System.Collections.Generic.HashSet<global::System.Type> s_compiledBehaviorTypes = new global::System.Collections.Generic.HashSet<global::System.Type>
        {
            typeof(global::TestApp.LoggingBehavior<,>),
            typeof(global::TestApp.ValidationBehavior<,>),
            typeof(global::TestApp.QueryLoggingBehavior<,>),
        };

        public static bool IsCompiledBehavior(global::System.Type behaviorType)
        {
            global::System.Type typeToCheck = behaviorType.IsGenericType ? behaviorType.GetGenericTypeDefinition() : behaviorType;
            return s_compiledBehaviorTypes.Contains(typeToCheck);
        }

        public static global::System.Type[] GetCompiledBehaviorTypes()
        {
            global::System.Type[] result = new global::System.Type[s_compiledBehaviorTypes.Count];
            s_compiledBehaviorTypes.CopyTo(result);
            return result;
        }
    }
}
