//HintName: NexumEndpointRegistration.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    /// <summary>
    /// Auto-generated endpoint registration for Nexum Minimal API endpoints.
    /// Generated by Nexum.SourceGenerators.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
    public static class NexumEndpointRegistration
    {
        /// <summary>
        /// Maps all Nexum endpoints decorated with [NexumEndpoint] attribute.
        /// </summary>
        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapNexumEndpoints(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
        {

            endpoints.MapDelete("/api/orders/{id}", async (
                global::TestApp.DeleteOrderCommand command,
                global::Nexum.Abstractions.ICommandDispatcher dispatcher,
                global::System.Threading.CancellationToken ct) =>
            {
                await dispatcher.DispatchAsync(command, ct).ConfigureAwait(false);
                return global::Microsoft.AspNetCore.Http.TypedResults.NoContent();
            })
            .WithName("DeleteOrder")
            .Produces(204)
            .ProducesProblem(400)
            ;
            return endpoints;
        }
    }
}
