//HintName: NexumHub_TestApp_OrderStreamHub.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    partial class OrderStreamHub
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
        public global::System.Collections.Generic.IAsyncEnumerable<global::System.String> StreamGetOrdersQuery(
            global::TestApp.GetOrdersQuery query,
            global::System.Threading.CancellationToken ct = default)
            => StreamQueryAsync<global::TestApp.GetOrdersQuery, global::System.String>(query, ct);
    }
}
