//HintName: NexumHub_TestApp_OrderStreamHub.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    partial class OrderStreamHub
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Nexum.SourceGenerators", "1.0.0")]
        public global::System.Collections.Generic.IAsyncEnumerable<global::System.String> StreamOrderUpdatedNotification(
            global::TestApp.OrderUpdatedNotification notification,
            global::System.Threading.CancellationToken ct = default)
            => StreamNotificationAsync<global::TestApp.OrderUpdatedNotification, global::System.String>(notification, ct);
    }
}
