using System.Text;

namespace Nexum.SourceGenerators
{
    /// <summary>
    /// Emits a partial class for each discovered [NexumStreamHub] class,
    /// generating concrete hub methods that call the protected base class helpers.
    /// </summary>
    internal static class NexumHubEmitter
    {
        public static string Emit(HubRegistration hub)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {hub.HubNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {hub.HubClassName}");
            sb.AppendLine("    {");

            bool first = true;
            foreach (HubMethodRegistration method in hub.Methods)
            {
                if (!first)
                {
                    sb.AppendLine();
                }
                first = false;

                EmitHubMethod(sb, method);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitHubMethod(StringBuilder sb, HubMethodRegistration method)
        {
            sb.AppendLine("        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Nexum.SourceGenerators\", \"1.0.0\")]");

            if (method.Kind == HandlerKind.StreamQuery)
            {
                sb.AppendLine($"        public global::System.Collections.Generic.IAsyncEnumerable<global::{method.ResultFullyQualifiedName}> {method.MethodName}(");
                sb.AppendLine($"            global::{method.MessageFullyQualifiedName} query,");
                sb.AppendLine($"            global::System.Threading.CancellationToken ct = default)");
                sb.AppendLine($"            => StreamQueryAsync<global::{method.MessageFullyQualifiedName}, global::{method.ResultFullyQualifiedName}>(query, ct);");
            }
            else // StreamNotification
            {
                sb.AppendLine($"        public global::System.Collections.Generic.IAsyncEnumerable<global::{method.ResultFullyQualifiedName}> {method.MethodName}(");
                sb.AppendLine($"            global::{method.MessageFullyQualifiedName} notification,");
                sb.AppendLine($"            global::System.Threading.CancellationToken ct = default)");
                sb.AppendLine($"            => StreamNotificationAsync<global::{method.MessageFullyQualifiedName}, global::{method.ResultFullyQualifiedName}>(notification, ct);");
            }
        }

        /// <summary>
        /// Derives a hub method name from the message class name.
        /// Prepends "Stream" to the simple class name (stripped of namespace).
        /// </summary>
        /// <remarks>
        /// Examples:
        /// <list type="bullet">
        ///   <item><description>GetOrderUpdatesQuery → StreamGetOrderUpdatesQuery</description></item>
        ///   <item><description>OrderUpdatesNotification → StreamOrderUpdatesNotification</description></item>
        /// </list>
        /// </remarks>
        public static string DeriveMethodName(string messageFullyQualifiedName)
        {
            int lastDot = messageFullyQualifiedName.LastIndexOf('.');
            string simpleName = lastDot >= 0
                ? messageFullyQualifiedName.Substring(lastDot + 1)
                : messageFullyQualifiedName;

            return "Stream" + simpleName;
        }
    }
}
