using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Nexum.SourceGenerators
{
    internal static class NexumPipelineRegistryEmitter
    {
        public static string Emit(
            string rootNamespace,
            EquatableArray<HandlerRegistration> handlers,
            EquatableArray<BehaviorRegistration> behaviors)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated pipeline registry with monomorphized dispatch methods.");
            sb.AppendLine("    /// Generated by Nexum.SourceGenerators (Tier 2).");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Nexum.SourceGenerators\", \"1.0.0\")]");
            sb.AppendLine("    internal static class NexumPipelineRegistry");
            sb.AppendLine("    {");

            // Group behaviors for lookup
            var behaviorList = new List<BehaviorRegistration>();
            foreach (BehaviorRegistration b in behaviors)
            {
                behaviorList.Add(b);
            }

            // Track which handlers get compiled pipelines
            var commandMethods = new Dictionary<string, string>();
            var queryMethods = new Dictionary<string, string>();
            var streamQueryMethods = new Dictionary<string, string>();

            // Track all compiled behavior types (for HashSet)
            var compiledBehaviorTypes = new HashSet<string>();

            // Generate dispatch methods for each handler (exclude Notification handlers)
            foreach (HandlerRegistration handler in handlers)
            {
                if (handler.Kind == HandlerKind.Notification)
                {
                    continue; // Skip notifications
                }

                // Find applicable behaviors for this handler
                List<BehaviorRegistration> applicableBehaviors = FindApplicableBehaviors(handler, behaviorList);

                // Track compiled behavior types
                foreach (BehaviorRegistration beh in applicableBehaviors)
                {
                    if (beh.IsOpenGeneric)
                    {
                        // Store open generic form: MyBehavior<,>
                        // Strip existing type parameters first
                        string baseFQN = beh.BehaviorFullyQualifiedName;
                        int genericIndex = baseFQN.IndexOf('<');
                        if (genericIndex > 0)
                        {
                            baseFQN = baseFQN.Substring(0, genericIndex);
                        }

                        string openGenericType = baseFQN + "<,>";
                        compiledBehaviorTypes.Add(openGenericType);
                    }
                    else
                    {
                        compiledBehaviorTypes.Add(beh.BehaviorFullyQualifiedName);
                    }
                }

                // Generate the method
                string methodName = GenerateMethodName(handler);
                EmitDispatchMethod(sb, handler, applicableBehaviors, methodName);

                // Track in lookup dictionary
                string messageType = $"typeof(global::{handler.MessageFullyQualifiedName})";
                switch (handler.Kind)
                {
                    case HandlerKind.Command:
                        commandMethods[messageType] = methodName;
                        break;
                    case HandlerKind.Query:
                        queryMethods[messageType] = methodName;
                        break;
                    case HandlerKind.StreamQuery:
                        streamQueryMethods[messageType] = methodName;
                        break;
                    case HandlerKind.Notification:
                        // Already filtered out above, should never reach here
                        break;
                    case HandlerKind.StreamNotification:
                        // StreamNotification handlers do not participate in pipeline delegate generation
                        break;
                    default:
                        // Unknown handler kind
                        break;
                }
            }

            sb.AppendLine();

            // Emit lookup dictionaries
            EmitLookupDictionary(sb, "s_commandMethods", commandMethods);
            EmitLookupDictionary(sb, "s_queryMethods", queryMethods);
            EmitLookupDictionary(sb, "s_streamQueryMethods", streamQueryMethods);

            sb.AppendLine();

            // Emit HasCompiled methods
            sb.AppendLine("        public static bool HasCompiledCommandPipeline(global::System.Type commandType)");
            sb.AppendLine("            => s_commandMethods.ContainsKey(commandType);");
            sb.AppendLine();
            sb.AppendLine("        public static bool HasCompiledQueryPipeline(global::System.Type queryType)");
            sb.AppendLine("            => s_queryMethods.ContainsKey(queryType);");
            sb.AppendLine();
            sb.AppendLine("        public static bool HasCompiledStreamQueryPipeline(global::System.Type queryType)");
            sb.AppendLine("            => s_streamQueryMethods.ContainsKey(queryType);");
            sb.AppendLine();

            // Emit GetMethodName methods
            sb.AppendLine("        public static string? GetCommandMethodName(global::System.Type commandType)");
            sb.AppendLine("            => s_commandMethods.TryGetValue(commandType, out var name) ? name : null;");
            sb.AppendLine();
            sb.AppendLine("        public static string? GetQueryMethodName(global::System.Type queryType)");
            sb.AppendLine("            => s_queryMethods.TryGetValue(queryType, out var name) ? name : null;");
            sb.AppendLine();
            sb.AppendLine("        public static string? GetStreamQueryMethodName(global::System.Type queryType)");
            sb.AppendLine("            => s_streamQueryMethods.TryGetValue(queryType, out var name) ? name : null;");
            sb.AppendLine();

            // Emit compiled behavior types HashSet and methods
            EmitCompiledBehaviorTypes(sb, compiledBehaviorTypes);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GenerateMethodName(HandlerRegistration handler)
        {
            string sanitized = SanitizeFQN(handler.MessageFullyQualifiedName);
            string prefix = handler.Kind == HandlerKind.StreamQuery ? "Stream_" : "Dispatch_";
            return prefix + sanitized;
        }

        private static string SanitizeFQN(string fqn)
        {
            return fqn.Replace(".", "_").Replace("+", "_");
        }

        private static List<BehaviorRegistration> FindApplicableBehaviors(
            HandlerRegistration handler,
            List<BehaviorRegistration> allBehaviors)
        {
            var applicable = new List<BehaviorRegistration>();

            // Convert handler kind to behavior kind
            BehaviorKind? behaviorKind = handler.Kind switch
            {
                HandlerKind.Command => BehaviorKind.Command,
                HandlerKind.Query => BehaviorKind.Query,
                HandlerKind.StreamQuery => BehaviorKind.StreamQuery,
                HandlerKind.Notification => null,
                HandlerKind.StreamNotification => null,
                _ => null
            };

            if (behaviorKind is null)
            {
                return applicable;
            }

            foreach (BehaviorRegistration behavior in allBehaviors)
            {
                if (behavior.Kind != behaviorKind.Value)
                {
                    continue;
                }

                if (behavior.IsOpenGeneric)
                {
                    // Open generic behaviors are always applicable to handlers of the same kind
                    applicable.Add(behavior);
                }
                else
                {
                    // Closed generic behaviors must match message and result types
                    if (behavior.MessageFullyQualifiedName == handler.MessageFullyQualifiedName
                        && behavior.ResultFullyQualifiedName == handler.ResultFullyQualifiedName)
                    {
                        applicable.Add(behavior);
                    }
                }
            }

            // Sort by Order ascending
            applicable.Sort((a, b) => a.Order.CompareTo(b.Order));

            return applicable;
        }

        private static void EmitDispatchMethod(
            StringBuilder sb,
            HandlerRegistration handler,
            List<BehaviorRegistration> applicableBehaviors,
            string methodName)
        {
            // Determine return type
            string returnType = handler.Kind == HandlerKind.StreamQuery
                ? $"global::System.Collections.Generic.IAsyncEnumerable<global::{handler.ResultFullyQualifiedName}>"
                : $"global::System.Threading.Tasks.ValueTask<global::{handler.ResultFullyQualifiedName}>";

            string messageTypeFQN = $"global::{handler.MessageFullyQualifiedName}";
            string paramName = handler.Kind is HandlerKind.Query or HandlerKind.StreamQuery
                ? "query"
                : "command";

            sb.AppendLine($"        public static {returnType}");
            sb.AppendLine($"            {methodName}(");
            sb.AppendLine($"                {messageTypeFQN} {paramName},");
            sb.AppendLine("                global::System.IServiceProvider sp,");
            sb.AppendLine("                global::System.Threading.CancellationToken ct)");
            sb.AppendLine("        {");

            // Resolve handler
            sb.AppendLine($"            var handler = global::Microsoft.Extensions.DependencyInjection");
            sb.AppendLine("                .ServiceProviderServiceExtensions");
            sb.AppendLine($"                .GetRequiredService<global::{handler.HandlerFullyQualifiedName}>(sp);");

            if (applicableBehaviors.Count == 0)
            {
                // No behaviors — directly call handler
                sb.AppendLine($"            return handler.HandleAsync({paramName}, ct);");
            }
            else
            {
                // Resolve all behaviors
                for (int i = 0; i < applicableBehaviors.Count; i++)
                {
                    BehaviorRegistration beh = applicableBehaviors[i];
                    string behaviorType = GetBehaviorType(beh, handler);
                    sb.AppendLine($"            var behavior{i + 1} = global::Microsoft.Extensions.DependencyInjection");
                    sb.AppendLine("                .ServiceProviderServiceExtensions");
                    sb.AppendLine($"                .GetRequiredService<{behaviorType}>(sp);");
                }

                // Build Russian doll pipeline
                sb.Append("            return ");
                BuildRussianDollPipeline(sb, applicableBehaviors.Count, paramName);
                sb.AppendLine(";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static string GetBehaviorType(BehaviorRegistration behavior, HandlerRegistration handler)
        {
            if (behavior.IsOpenGeneric)
            {
                // For open generic behaviors, BehaviorFullyQualifiedName includes type parameters like "MyBehavior<TCmd, TRes>"
                // We need to strip them and replace with the actual handler's message and result types
                string baseFQN = behavior.BehaviorFullyQualifiedName;
                int genericIndex = baseFQN.IndexOf('<');
                if (genericIndex > 0)
                {
                    baseFQN = baseFQN.Substring(0, genericIndex);
                }

                return $"global::{baseFQN}<global::{handler.MessageFullyQualifiedName}, global::{handler.ResultFullyQualifiedName}>";
            }

            // Already closed
            return $"global::{behavior.BehaviorFullyQualifiedName}";
        }

        private static void BuildRussianDollPipeline(StringBuilder sb, int behaviorCount, string paramName)
        {
            // Build nested pipeline: behavior1.HandleAsync(msg, ct2 => behavior2.HandleAsync(...), ct)
            for (int i = 1; i <= behaviorCount; i++)
            {
                sb.Append($"behavior{i}.HandleAsync({paramName},");
                sb.AppendLine();
                sb.Append($"                ct{i + 1} => ");
            }

            // Innermost: handler.HandleAsync
            sb.Append($"handler.HandleAsync({paramName}, ct{behaviorCount + 1})");

            // Close all behavior calls (closing in reverse order)
            for (int i = behaviorCount; i >= 1; i--)
            {
                // The outermost behavior receives "ct", inner behaviors receive "ct2", "ct3", etc.
                string ctParam = i == 1 ? "ct" : $"ct{i}";
                sb.Append($", {ctParam})");
                if (i > 1)
                {
                    sb.AppendLine();
                    sb.Append("                ");
                }
            }
        }

        private static void EmitLookupDictionary(StringBuilder sb, string fieldName, Dictionary<string, string> entries)
        {
            sb.AppendLine($"        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> {fieldName} = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
            sb.AppendLine("        {");

            foreach (KeyValuePair<string, string> kvp in entries)
            {
                sb.AppendLine($"            [{kvp.Key}] = nameof({kvp.Value}),");
            }

            sb.AppendLine("        };");
        }

        private static void EmitCompiledBehaviorTypes(StringBuilder sb, HashSet<string> behaviorTypes)
        {
            sb.AppendLine("        private static readonly global::System.Collections.Generic.HashSet<global::System.Type> s_compiledBehaviorTypes = new global::System.Collections.Generic.HashSet<global::System.Type>");
            sb.AppendLine("        {");

            foreach (string behaviorType in behaviorTypes)
            {
                sb.AppendLine($"            typeof(global::{behaviorType}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine("        public static bool IsCompiledBehavior(global::System.Type behaviorType)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.Type typeToCheck = behaviorType.IsGenericType ? behaviorType.GetGenericTypeDefinition() : behaviorType;");
            sb.AppendLine("            return s_compiledBehaviorTypes.Contains(typeToCheck);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static global::System.Type[] GetCompiledBehaviorTypes()");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.Type[] result = new global::System.Type[s_compiledBehaviorTypes.Count];");
            sb.AppendLine("            s_compiledBehaviorTypes.CopyTo(result);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
        }
    }
}
