using System.Text;

namespace Nexum.SourceGenerators
{
    internal static class NexumHandlerRegistryEmitter
    {
        public static string Emit(string rootNamespace, EquatableArray<HandlerRegistration> registrations)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated handler registry for Nexum DI registration.");
            sb.AppendLine("    /// Generated by Nexum.SourceGenerators (Tier 1).");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Nexum.SourceGenerators\", \"1.0.0\")]");
            sb.AppendLine("    internal static class NexumHandlerRegistry");
            sb.AppendLine("    {");

            // AddNexumHandlers method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Registers all discovered Nexum handlers with the service collection.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void AddNexumHandlers(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("        {");
            foreach (HandlerRegistration reg in registrations)
            {
                string msdiLifetime = MapToServiceLifetime(reg.Lifetime);
                sb.AppendLine($"            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
                sb.AppendLine($"                typeof(global::{reg.ServiceInterfaceFullyQualifiedName}),");
                sb.AppendLine($"                typeof(global::{reg.HandlerFullyQualifiedName}),");
                sb.AppendLine($"                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.{msdiLifetime}));");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // GetAllRegistrations method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Returns all handler registrations for non-MSDI containers.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static global::System.Collections.Generic.IEnumerable<(global::System.Type ServiceType, global::System.Type ImplementationType, global::Nexum.Abstractions.NexumLifetime Lifetime)> GetAllRegistrations()");
            sb.AppendLine("        {");
            foreach (HandlerRegistration reg in registrations)
            {
                string nexumLifetime = MapToNexumLifetime(reg.Lifetime);
                sb.AppendLine($"            yield return (typeof(global::{reg.ServiceInterfaceFullyQualifiedName}), typeof(global::{reg.HandlerFullyQualifiedName}), global::Nexum.Abstractions.NexumLifetime.{nexumLifetime});");
            }

            // If no registrations, need to make it valid C# (iterator must contain yield)
            if (registrations.Length == 0)
            {
                sb.AppendLine("            yield break;");
            }

            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string MapToServiceLifetime(string? lifetime)
        {
            // Default is Scoped for handlers
            return lifetime is null
                ? "Scoped"
                : lifetime switch
                {
                    "Transient" => "Transient",
                    "Scoped" => "Scoped",
                    "Singleton" => "Singleton",
                    _ => "Scoped"
                };
        }

        private static string MapToNexumLifetime(string? lifetime)
        {
            return lifetime is null
                ? "Scoped"
                : lifetime switch
                {
                    "Transient" => "Transient",
                    "Scoped" => "Scoped",
                    "Singleton" => "Singleton",
                    _ => "Scoped"
                };
        }
    }
}
