using System.Text;

namespace Nexum.SourceGenerators
{
    internal static class NexumEndpointEmitter
    {
        public static string Emit(string rootNamespace, EquatableArray<EndpointRegistration> endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated endpoint registration for Nexum Minimal API endpoints.");
            sb.AppendLine("    /// Generated by Nexum.SourceGenerators.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Nexum.SourceGenerators\", \"1.0.0\")]");
            sb.AppendLine("    public static class NexumEndpointRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Maps all Nexum endpoints decorated with [NexumEndpoint] attribute.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapNexumEndpoints(");
            sb.AppendLine("            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)");
            sb.AppendLine("        {");

            foreach (EndpointRegistration ep in endpoints)
            {
                EmitEndpoint(sb, ep);
            }

            sb.AppendLine("            return endpoints;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitEndpoint(StringBuilder sb, EndpointRegistration ep)
        {
            string aspNetMethod = ep.HttpMethod switch
            {
                "Get" => "MapGet",
                "Post" => "MapPost",
                "Put" => "MapPut",
                "Delete" => "MapDelete",
                "Patch" => "MapPatch",
                _ => "MapPost"
            };

            string endpointName = ep.Name ?? DeriveEndpointName(ep.MessageFullyQualifiedName, ep.Kind);

            sb.AppendLine();

            bool isVoidCommand = ep.Kind == HandlerKind.Command && ep.ResultFullyQualifiedName == "Nexum.Abstractions.Unit";
            bool isQuery = ep.Kind == HandlerKind.Query;

            if (isVoidCommand)
            {
                EmitVoidCommandEndpoint(sb, ep, aspNetMethod, endpointName);
            }
            else if (isQuery)
            {
                EmitQueryEndpoint(sb, ep, aspNetMethod, endpointName);
            }
            else
            {
                EmitCommandWithResultEndpoint(sb, ep, aspNetMethod, endpointName);
            }
        }

        private static void EmitVoidCommandEndpoint(StringBuilder sb, EndpointRegistration ep, string aspNetMethod, string endpointName)
        {
            sb.AppendLine($"            endpoints.{aspNetMethod}(\"{ep.Pattern}\", async (");
            sb.AppendLine($"                global::{ep.MessageFullyQualifiedName} command,");
            sb.AppendLine($"                global::Nexum.Abstractions.ICommandDispatcher dispatcher,");
            sb.AppendLine($"                global::System.Threading.CancellationToken ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                await dispatcher.DispatchAsync(command, ct).ConfigureAwait(false);");
            sb.AppendLine("                return global::Microsoft.AspNetCore.Http.TypedResults.NoContent();");
            sb.AppendLine("            })");
            sb.AppendLine($"            .WithName(\"{endpointName}\")");
            sb.AppendLine("            .Produces(204)");
            AppendProducesProblem(sb);
            AppendTags(sb, ep.GroupName);
            sb.AppendLine("            ;");
        }

        private static void EmitQueryEndpoint(StringBuilder sb, EndpointRegistration ep, string aspNetMethod, string endpointName)
        {
            sb.AppendLine($"            endpoints.{aspNetMethod}(\"{ep.Pattern}\", async (");
            sb.AppendLine($"                [global::Microsoft.AspNetCore.Http.AsParameters] global::{ep.MessageFullyQualifiedName} query,");
            sb.AppendLine($"                global::Nexum.Abstractions.IQueryDispatcher dispatcher,");
            sb.AppendLine($"                global::System.Threading.CancellationToken ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var result = await dispatcher.DispatchAsync(query, ct).ConfigureAwait(false);");

            if (ep.HasResultMembers)
            {
                sb.AppendLine("                if (result.IsSuccess)");
                sb.AppendLine("                {");
                sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.Results.Ok(result.Value);");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                var error = result.Error;");
                sb.AppendLine("                if (error is not null)");
                sb.AppendLine("                {");
                sb.AppendLine("                    var pd = new global::Microsoft.AspNetCore.Mvc.ProblemDetails");
                sb.AppendLine("                    {");
                sb.AppendLine("                        Status = 400,");
                sb.AppendLine("                        Title = \"Request Failed\",");
                sb.AppendLine("                        Detail = error.ToString()");
                sb.AppendLine("                    };");
                sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.Results.Problem(pd);");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                return global::Microsoft.AspNetCore.Http.Results.Ok(result.Value);");
            }
            else
            {
                sb.AppendLine($"                return global::Microsoft.AspNetCore.Http.TypedResults.Ok(result);");
            }

            sb.AppendLine("            })");
            sb.AppendLine($"            .WithName(\"{endpointName}\")");
            if (ep.HasResultMembers)
            {
                sb.AppendLine($"            .Produces<object>(200)");
            }
            else
            {
                sb.AppendLine($"            .Produces<global::{ep.ResultFullyQualifiedName}>(200)");
            }
            AppendProducesProblem(sb);
            AppendTags(sb, ep.GroupName);
            sb.AppendLine("            ;");
        }

        private static void EmitCommandWithResultEndpoint(StringBuilder sb, EndpointRegistration ep, string aspNetMethod, string endpointName)
        {
            sb.AppendLine($"            endpoints.{aspNetMethod}(\"{ep.Pattern}\", async (");
            sb.AppendLine($"                global::{ep.MessageFullyQualifiedName} command,");
            sb.AppendLine($"                global::Nexum.Abstractions.ICommandDispatcher dispatcher,");
            sb.AppendLine($"                global::System.Threading.CancellationToken ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var result = await dispatcher.DispatchAsync(command, ct).ConfigureAwait(false);");

            if (ep.HasResultMembers)
            {
                sb.AppendLine("                if (result.IsSuccess)");
                sb.AppendLine("                {");
                sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.Results.Ok(result.Value);");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                var error = result.Error;");
                sb.AppendLine("                if (error is not null)");
                sb.AppendLine("                {");
                sb.AppendLine("                    var pd = new global::Microsoft.AspNetCore.Mvc.ProblemDetails");
                sb.AppendLine("                    {");
                sb.AppendLine("                        Status = 400,");
                sb.AppendLine("                        Title = \"Request Failed\",");
                sb.AppendLine("                        Detail = error.ToString()");
                sb.AppendLine("                    };");
                sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.Results.Problem(pd);");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                return global::Microsoft.AspNetCore.Http.Results.Ok(result.Value);");
            }
            else
            {
                sb.AppendLine($"                return global::Microsoft.AspNetCore.Http.TypedResults.Ok(result);");
            }

            sb.AppendLine("            })");
            sb.AppendLine($"            .WithName(\"{endpointName}\")");
            if (ep.HasResultMembers)
            {
                sb.AppendLine($"            .Produces<object>(200)");
            }
            else
            {
                sb.AppendLine($"            .Produces<global::{ep.ResultFullyQualifiedName}>(200)");
            }
            AppendProducesProblem(sb);
            AppendTags(sb, ep.GroupName);
            sb.AppendLine("            ;");
        }

        private static void AppendProducesProblem(StringBuilder sb)
        {
            sb.AppendLine("            .ProducesProblem(400)");
        }

        private static void AppendTags(StringBuilder sb, string? groupName)
        {
            if (groupName is not null)
            {
                sb.AppendLine($"            .WithTags(\"{groupName}\")");
            }
        }

        private static string DeriveEndpointName(string messageFullyQualifiedName, HandlerKind _)
        {
            // Get simple type name from FQN
            int lastDot = messageFullyQualifiedName.LastIndexOf('.');
            string typeName = lastDot >= 0
                ? messageFullyQualifiedName.Substring(lastDot + 1)
                : messageFullyQualifiedName;

            // Strip suffix
            return typeName.EndsWith("Command")
                ? typeName.Substring(0, typeName.Length - "Command".Length)
                : typeName.EndsWith("Query")
                    ? typeName.Substring(0, typeName.Length - "Query".Length)
                    : typeName;
        }
    }
}
