using System;
using System.Collections.Generic;
using System.Text;

namespace Nexum.SourceGenerators
{
    internal static class NexumInterceptorEmitter
    {
        /// <summary>
        /// Emits the NexumInterceptors.g.cs source for all discovered call-sites.
        /// </summary>
        /// <param name="rootNamespace">Consumer's root namespace</param>
        /// <param name="callSites">Discovered interceptor call-sites</param>
        /// <param name="handlers">Registered handlers (to determine if Tier 2 exists)</param>
        /// <param name="hasPipelineRegistry">Whether NexumPipelineRegistry was generated (Tier 2)</param>
        /// <returns>Generated source code string</returns>
        public static string Emit(
            string rootNamespace,
            EquatableArray<InterceptorCallSite> callSites,
            EquatableArray<HandlerRegistration> handlers,
            bool hasPipelineRegistry)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            // Emit InterceptsLocationAttribute definition (required for interceptors)
            sb.AppendLine("#pragma warning disable CS9113 // Parameter is unread");
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    using System;");
            sb.AppendLine();
            sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
            sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#pragma warning restore CS9113");
            sb.AppendLine();

            sb.AppendLine($"namespace {rootNamespace}.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated interceptor methods for Nexum dispatcher calls.");
            sb.AppendLine("    /// Generated by Nexum.SourceGenerators (Tier 3).");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Nexum.SourceGenerators\", \"1.0.0\")]");
            sb.AppendLine("    file static class NexumInterceptors");
            sb.AppendLine("    {");

            // Build handler lookup for determining if Tier 2 pipeline exists
            var handlerLookup = new Dictionary<string, HandlerRegistration>();
            foreach (HandlerRegistration handler in handlers)
            {
                handlerLookup[handler.MessageFullyQualifiedName] = handler;
            }

            // Generate interceptor methods for each call-site
            int interceptorIndex = 1;
            foreach (InterceptorCallSite callSite in callSites)
            {
                EmitInterceptorMethod(
                    sb,
                    callSite,
                    rootNamespace,
                    interceptorIndex,
                    hasPipelineRegistry,
                    handlerLookup);
                interceptorIndex++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitInterceptorMethod(
            StringBuilder sb,
            InterceptorCallSite callSite,
            string rootNamespace,
            int index,
            bool hasPipelineRegistry,
            Dictionary<string, HandlerRegistration> handlerLookup)
        {
            string methodName = $"Intercept_DispatchAsync_{index:D4}";
            string messageFQN = callSite.MessageFullyQualifiedName;

            // Always resolve handler from lookup (needed for both Tier 2 and direct call paths)
            handlerLookup.TryGetValue(messageFQN, out HandlerRegistration? handler);
            bool hasCompiledPipeline = hasPipelineRegistry && handler is not null;

            // Emit [InterceptsLocation] attribute
            sb.AppendLine($"        {callSite.InterceptsLocationSyntax}");

            // Emit method signature based on interceptor kind
            switch (callSite.Kind)
            {
                case InterceptorKind.Command:
                    EmitCommandInterceptor(sb, callSite, methodName, rootNamespace, hasCompiledPipeline, handler);
                    break;
                case InterceptorKind.Query:
                    EmitQueryInterceptor(sb, callSite, methodName, rootNamespace, hasCompiledPipeline, handler);
                    break;
                case InterceptorKind.StreamQuery:
                    EmitStreamQueryInterceptor(sb, callSite, methodName, rootNamespace, hasCompiledPipeline, handler);
                    break;
                default:
                    // Unknown kind - should never happen in validated data
                    break;
            }

            sb.AppendLine();
        }

        private static void EmitCommandInterceptor(
            StringBuilder sb,
            InterceptorCallSite callSite,
            string methodName,
            string rootNamespace,
            bool hasCompiledPipeline,
            HandlerRegistration? handler)
        {
            string messageFQN = callSite.MessageFullyQualifiedName;
            string resultFQN = callSite.ResultFullyQualifiedName;

            sb.AppendLine("        internal static global::System.Threading.Tasks.ValueTask<TResult>");
            sb.AppendLine($"            {methodName}<TResult>(");
            sb.AppendLine("                this global::Nexum.Abstractions.ICommandDispatcher @this,");
            sb.AppendLine("                global::Nexum.Abstractions.ICommand<TResult> command,");
            sb.AppendLine("                global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var __result = ((global::Nexum.IInterceptableDispatcher)@this)");
            sb.AppendLine($"                .DispatchInterceptedCommandAsync<global::{messageFQN}, global::{resultFQN}>(");
            sb.AppendLine($"                    (global::{messageFQN})(object)command,");
            sb.AppendLine("                    static (cmd, sp, ct) =>");
            sb.AppendLine("                    {");

            if (hasCompiledPipeline)
            {
                // Use Tier 2 compiled pipeline
                string pipelineMethodName = GeneratePipelineMethodName(handler!);
                sb.AppendLine($"                        return global::{rootNamespace}.NexumPipelineRegistry.{pipelineMethodName}(cmd, sp, ct);");
            }
            else
            {
                // Direct handler call (no Tier 2)
                // Handler is guaranteed non-null here (generator filters out call-sites without known handlers)
                string handlerFQN = handler!.HandlerFullyQualifiedName;
                sb.AppendLine("                        var handler = global::Microsoft.Extensions.DependencyInjection");
                sb.AppendLine("                            .ServiceProviderServiceExtensions");
                sb.AppendLine($"                            .GetRequiredService<global::{handlerFQN}>(sp);");
                sb.AppendLine("                        return handler.HandleAsync(cmd, ct);");
            }

            sb.AppendLine("                    },");
            sb.AppendLine("                    ct);");
            sb.Append("            return global::System.Runtime.CompilerServices.Unsafe.As<");
            sb.Append($"global::System.Threading.Tasks.ValueTask<global::{resultFQN}>, ");
            sb.AppendLine("global::System.Threading.Tasks.ValueTask<TResult>>(ref __result);");
            sb.AppendLine("        }");
        }

        private static void EmitQueryInterceptor(
            StringBuilder sb,
            InterceptorCallSite callSite,
            string methodName,
            string rootNamespace,
            bool hasCompiledPipeline,
            HandlerRegistration? handler)
        {
            string messageFQN = callSite.MessageFullyQualifiedName;
            string resultFQN = callSite.ResultFullyQualifiedName;

            sb.AppendLine("        internal static global::System.Threading.Tasks.ValueTask<TResult>");
            sb.AppendLine($"            {methodName}<TResult>(");
            sb.AppendLine("                this global::Nexum.Abstractions.IQueryDispatcher @this,");
            sb.AppendLine("                global::Nexum.Abstractions.IQuery<TResult> query,");
            sb.AppendLine("                global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var __result = ((global::Nexum.IInterceptableDispatcher)@this)");
            sb.AppendLine($"                .DispatchInterceptedQueryAsync<global::{messageFQN}, global::{resultFQN}>(");
            sb.AppendLine($"                    (global::{messageFQN})(object)query,");
            sb.AppendLine("                    static (qry, sp, ct) =>");
            sb.AppendLine("                    {");

            if (hasCompiledPipeline)
            {
                // Use Tier 2 compiled pipeline
                string pipelineMethodName = GeneratePipelineMethodName(handler!);
                sb.AppendLine($"                        return global::{rootNamespace}.NexumPipelineRegistry.{pipelineMethodName}(qry, sp, ct);");
            }
            else
            {
                // Direct handler call (no Tier 2)
                // Handler is guaranteed non-null here (generator filters out call-sites without known handlers)
                string handlerFQN = handler!.HandlerFullyQualifiedName;
                sb.AppendLine("                        var handler = global::Microsoft.Extensions.DependencyInjection");
                sb.AppendLine("                            .ServiceProviderServiceExtensions");
                sb.AppendLine($"                            .GetRequiredService<global::{handlerFQN}>(sp);");
                sb.AppendLine("                        return handler.HandleAsync(qry, ct);");
            }

            sb.AppendLine("                    },");
            sb.AppendLine("                    ct);");
            sb.Append("            return global::System.Runtime.CompilerServices.Unsafe.As<");
            sb.Append($"global::System.Threading.Tasks.ValueTask<global::{resultFQN}>, ");
            sb.AppendLine("global::System.Threading.Tasks.ValueTask<TResult>>(ref __result);");
            sb.AppendLine("        }");
        }

        private static void EmitStreamQueryInterceptor(
            StringBuilder sb,
            InterceptorCallSite callSite,
            string methodName,
            string rootNamespace,
            bool hasCompiledPipeline,
            HandlerRegistration? handler)
        {
            string messageFQN = callSite.MessageFullyQualifiedName;
            string resultFQN = callSite.ResultFullyQualifiedName;

            sb.AppendLine("        internal static global::System.Collections.Generic.IAsyncEnumerable<TResult>");
            sb.AppendLine($"            {methodName}<TResult>(");
            sb.AppendLine("                this global::Nexum.Abstractions.IQueryDispatcher @this,");
            sb.AppendLine("                global::Nexum.Abstractions.IStreamQuery<TResult> query,");
            sb.AppendLine("                global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var __result = ((global::Nexum.IInterceptableDispatcher)@this)");
            sb.AppendLine($"                .StreamInterceptedAsync<global::{messageFQN}, global::{resultFQN}>(");
            sb.AppendLine($"                    (global::{messageFQN})(object)query,");
            sb.AppendLine("                    static (qry, sp, ct) =>");
            sb.AppendLine("                    {");

            if (hasCompiledPipeline)
            {
                // Use Tier 2 compiled pipeline
                string pipelineMethodName = GeneratePipelineMethodName(handler!);
                sb.AppendLine($"                        return global::{rootNamespace}.NexumPipelineRegistry.{pipelineMethodName}(qry, sp, ct);");
            }
            else
            {
                // Direct handler call (no Tier 2)
                // Handler is guaranteed non-null here (generator filters out call-sites without known handlers)
                string handlerFQN = handler!.HandlerFullyQualifiedName;
                sb.AppendLine("                        var handler = global::Microsoft.Extensions.DependencyInjection");
                sb.AppendLine("                            .ServiceProviderServiceExtensions");
                sb.AppendLine($"                            .GetRequiredService<global::{handlerFQN}>(sp);");
                sb.AppendLine("                        return handler.HandleAsync(qry, ct);");
            }

            sb.AppendLine("                    },");
            sb.AppendLine("                    ct);");
            sb.AppendLine("            return global::System.Runtime.CompilerServices.Unsafe");
            sb.AppendLine($"                .As<global::System.Collections.Generic.IAsyncEnumerable<global::{resultFQN}>,");
            sb.AppendLine("                    global::System.Collections.Generic.IAsyncEnumerable<TResult>>(ref __result);");
            sb.AppendLine("        }");
        }

        private static string GeneratePipelineMethodName(HandlerRegistration handler)
        {
            string sanitized = SanitizeFQN(handler.MessageFullyQualifiedName);
            string prefix = handler.Kind == HandlerKind.StreamQuery ? "Stream_" : "Dispatch_";
            return prefix + sanitized;
        }

        private static string SanitizeFQN(string fqn)
        {
            return fqn.Replace(".", "_").Replace("+", "_");
        }
    }
}
